(cl:in-package f110_msgs-msg)
(cl:export '(ID-VAL
          ID
          S_START-VAL
          S_START
          S_END-VAL
          S_END
          D_RIGHT-VAL
          D_RIGHT
          D_LEFT-VAL
          D_LEFT
          IS_ACTUALLY_A_GAP-VAL
          IS_ACTUALLY_A_GAP
          S_CENTER-VAL
          S_CENTER
          D_CENTER-VAL
          D_CENTER
          SIZE-VAL
          SIZE
          VS-VAL
          VS
          VD-VAL
          VD
          S_VAR-VAL
          S_VAR
          D_VAR-VAL
          D_VAR
          VS_VAR-VAL
          VS_VAR
          VD_VAR-VAL
          VD_VAR
          IS_STATIC-VAL
          IS_STATIC
          IS_VISIBLE-VAL
          IS_VISIBLE
))