# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from f110_msgs/Wpnt.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Wpnt(genpy.Message):
  _md5sum = "13f150fd4a210ecd18beb652ce35aefa"
  _type = "f110_msgs/Wpnt"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 id

# frenet coordinates
float64 s_m
float64 d_m

# map coordinates
float64 x_m
float64 y_m

# track bound distance
float64 d_right
float64 d_left

# track information
float64 psi_rad
float64 kappa_radpm
float64 vx_mps
float64 ax_mps2

"""
  __slots__ = ['id','s_m','d_m','x_m','y_m','d_right','d_left','psi_rad','kappa_radpm','vx_mps','ax_mps2']
  _slot_types = ['int32','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,s_m,d_m,x_m,y_m,d_right,d_left,psi_rad,kappa_radpm,vx_mps,ax_mps2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Wpnt, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.s_m is None:
        self.s_m = 0.
      if self.d_m is None:
        self.d_m = 0.
      if self.x_m is None:
        self.x_m = 0.
      if self.y_m is None:
        self.y_m = 0.
      if self.d_right is None:
        self.d_right = 0.
      if self.d_left is None:
        self.d_left = 0.
      if self.psi_rad is None:
        self.psi_rad = 0.
      if self.kappa_radpm is None:
        self.kappa_radpm = 0.
      if self.vx_mps is None:
        self.vx_mps = 0.
      if self.ax_mps2 is None:
        self.ax_mps2 = 0.
    else:
      self.id = 0
      self.s_m = 0.
      self.d_m = 0.
      self.x_m = 0.
      self.y_m = 0.
      self.d_right = 0.
      self.d_left = 0.
      self.psi_rad = 0.
      self.kappa_radpm = 0.
      self.vx_mps = 0.
      self.ax_mps2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i10d().pack(_x.id, _x.s_m, _x.d_m, _x.x_m, _x.y_m, _x.d_right, _x.d_left, _x.psi_rad, _x.kappa_radpm, _x.vx_mps, _x.ax_mps2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 84
      (_x.id, _x.s_m, _x.d_m, _x.x_m, _x.y_m, _x.d_right, _x.d_left, _x.psi_rad, _x.kappa_radpm, _x.vx_mps, _x.ax_mps2,) = _get_struct_i10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i10d().pack(_x.id, _x.s_m, _x.d_m, _x.x_m, _x.y_m, _x.d_right, _x.d_left, _x.psi_rad, _x.kappa_radpm, _x.vx_mps, _x.ax_mps2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 84
      (_x.id, _x.s_m, _x.d_m, _x.x_m, _x.y_m, _x.d_right, _x.d_left, _x.psi_rad, _x.kappa_radpm, _x.vx_mps, _x.ax_mps2,) = _get_struct_i10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i10d = None
def _get_struct_i10d():
    global _struct_i10d
    if _struct_i10d is None:
        _struct_i10d = struct.Struct("<i10d")
    return _struct_i10d
