//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the perception package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __perception__DYN_TRACKER_TUNERCONFIG_H__
#define __perception__DYN_TRACKER_TUNERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace perception
{
  class dyn_tracker_tunerConfigStatics;

  class dyn_tracker_tunerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(dyn_tracker_tunerConfig &config, const dyn_tracker_tunerConfig &max, const dyn_tracker_tunerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const dyn_tracker_tunerConfig &config1, const dyn_tracker_tunerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, dyn_tracker_tunerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const dyn_tracker_tunerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, dyn_tracker_tunerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const dyn_tracker_tunerConfig &config) const = 0;
      virtual void getValue(const dyn_tracker_tunerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T dyn_tracker_tunerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T dyn_tracker_tunerConfig::* field;

      virtual void clamp(dyn_tracker_tunerConfig &config, const dyn_tracker_tunerConfig &max, const dyn_tracker_tunerConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const dyn_tracker_tunerConfig &config1, const dyn_tracker_tunerConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, dyn_tracker_tunerConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const dyn_tracker_tunerConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, dyn_tracker_tunerConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const dyn_tracker_tunerConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const dyn_tracker_tunerConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, dyn_tracker_tunerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, dyn_tracker_tunerConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<dyn_tracker_tunerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(dyn_tracker_tunerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("ttl_dynamic"==(*_i)->name){ttl_dynamic = boost::any_cast<int>(val);}
        if("ratio_to_glob_path"==(*_i)->name){ratio_to_glob_path = boost::any_cast<double>(val);}
        if("ttl_static"==(*_i)->name){ttl_static = boost::any_cast<int>(val);}
        if("min_nb_meas"==(*_i)->name){min_nb_meas = boost::any_cast<int>(val);}
        if("dist_deletion"==(*_i)->name){dist_deletion = boost::any_cast<double>(val);}
        if("dist_infront"==(*_i)->name){dist_infront = boost::any_cast<double>(val);}
        if("min_std"==(*_i)->name){min_std = boost::any_cast<double>(val);}
        if("max_std"==(*_i)->name){max_std = boost::any_cast<double>(val);}
        if("vs_reset"==(*_i)->name){vs_reset = boost::any_cast<double>(val);}
        if("aggro_multi"==(*_i)->name){aggro_multi = boost::any_cast<double>(val);}
        if("debug_mode"==(*_i)->name){debug_mode = boost::any_cast<bool>(val);}
        if("publish_static"==(*_i)->name){publish_static = boost::any_cast<bool>(val);}
        if("noMemoryMode"==(*_i)->name){noMemoryMode = boost::any_cast<bool>(val);}
        if("min_obs_size"==(*_i)->name){min_obs_size = boost::any_cast<int>(val);}
        if("max_obs_size"==(*_i)->name){max_obs_size = boost::any_cast<double>(val);}
        if("max_viewing_distance"==(*_i)->name){max_viewing_distance = boost::any_cast<double>(val);}
        if("boundaries_inflation"==(*_i)->name){boundaries_inflation = boost::any_cast<double>(val);}
      }
    }

    int ttl_dynamic;
double ratio_to_glob_path;
int ttl_static;
int min_nb_meas;
double dist_deletion;
double dist_infront;
double min_std;
double max_std;
double vs_reset;
double aggro_multi;
bool debug_mode;
bool publish_static;
bool noMemoryMode;
int min_obs_size;
double max_obs_size;
double max_viewing_distance;
double boundaries_inflation;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int ttl_dynamic;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ratio_to_glob_path;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int ttl_static;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_nb_meas;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double dist_deletion;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double dist_infront;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_std;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_std;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vs_reset;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double aggro_multi;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool debug_mode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool publish_static;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool noMemoryMode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_obs_size;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_obs_size;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_viewing_distance;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double boundaries_inflation;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("dyn_tracker_tunerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const dyn_tracker_tunerConfig &__max__ = __getMax__();
      const dyn_tracker_tunerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const dyn_tracker_tunerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const dyn_tracker_tunerConfig &__getDefault__();
    static const dyn_tracker_tunerConfig &__getMax__();
    static const dyn_tracker_tunerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const dyn_tracker_tunerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void dyn_tracker_tunerConfig::ParamDescription<std::string>::clamp(dyn_tracker_tunerConfig &config, const dyn_tracker_tunerConfig &max, const dyn_tracker_tunerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class dyn_tracker_tunerConfigStatics
  {
    friend class dyn_tracker_tunerConfig;

    dyn_tracker_tunerConfigStatics()
    {
dyn_tracker_tunerConfig::GroupDescription<dyn_tracker_tunerConfig::DEFAULT, dyn_tracker_tunerConfig> Default("Default", "", 0, 0, true, &dyn_tracker_tunerConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ttl_dynamic = 5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ttl_dynamic = 300;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ttl_dynamic = 40;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<int>("ttl_dynamic", "int", 0, "Time to live of dynamic preditction from kalman filter", "", &dyn_tracker_tunerConfig::ttl_dynamic)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<int>("ttl_dynamic", "int", 0, "Time to live of dynamic preditction from kalman filter", "", &dyn_tracker_tunerConfig::ttl_dynamic)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ratio_to_glob_path = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ratio_to_glob_path = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ratio_to_glob_path = 0.6;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("ratio_to_glob_path", "double", 0, "the ratio between the target velocity and the global velocity", "", &dyn_tracker_tunerConfig::ratio_to_glob_path)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("ratio_to_glob_path", "double", 0, "the ratio between the target velocity and the global velocity", "", &dyn_tracker_tunerConfig::ratio_to_glob_path)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ttl_static = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ttl_static = 20;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ttl_static = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<int>("ttl_static", "int", 0, "time to live of static and not classified obstacles", "", &dyn_tracker_tunerConfig::ttl_static)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<int>("ttl_static", "int", 0, "time to live of static and not classified obstacles", "", &dyn_tracker_tunerConfig::ttl_static)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_nb_meas = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_nb_meas = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_nb_meas = 5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<int>("min_nb_meas", "int", 0, "minimum number of measurments before classifying an object", "", &dyn_tracker_tunerConfig::min_nb_meas)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<int>("min_nb_meas", "int", 0, "minimum number of measurments before classifying an object", "", &dyn_tracker_tunerConfig::min_nb_meas)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dist_deletion = 3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dist_deletion = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dist_deletion = 7.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("dist_deletion", "double", 0, "distance in which obstacles can be deleted", "", &dyn_tracker_tunerConfig::dist_deletion)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("dist_deletion", "double", 0, "distance in which obstacles can be deleted", "", &dyn_tracker_tunerConfig::dist_deletion)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dist_infront = 3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dist_infront = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dist_infront = 8.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("dist_infront", "double", 0, "obstacles infront of the car by this distance are published", "", &dyn_tracker_tunerConfig::dist_infront)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("dist_infront", "double", 0, "obstacles infront of the car by this distance are published", "", &dyn_tracker_tunerConfig::dist_infront)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_std = 0.05;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_std = 0.3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_std = 0.16;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("min_std", "double", 0, "minimum standard deviation under which obstacles are classified as static", "", &dyn_tracker_tunerConfig::min_std)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("min_std", "double", 0, "minimum standard deviation under which obstacles are classified as static", "", &dyn_tracker_tunerConfig::min_std)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_std = 0.15;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_std = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_std = 0.2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("max_std", "double", 0, "mamixmum standard deviation over which obstacles are classified as dynamic", "", &dyn_tracker_tunerConfig::max_std)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("max_std", "double", 0, "mamixmum standard deviation over which obstacles are classified as dynamic", "", &dyn_tracker_tunerConfig::max_std)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vs_reset = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vs_reset = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vs_reset = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("vs_reset", "double", 0, "average velocity in s direction under which dynamic obstacle gets reset to static", "", &dyn_tracker_tunerConfig::vs_reset)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("vs_reset", "double", 0, "average velocity in s direction under which dynamic obstacle gets reset to static", "", &dyn_tracker_tunerConfig::vs_reset)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.aggro_multi = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.aggro_multi = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.aggro_multi = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("aggro_multi", "double", 0, "multplies the association distance for dynamic obstacles", "", &dyn_tracker_tunerConfig::aggro_multi)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("aggro_multi", "double", 0, "multplies the association distance for dynamic obstacles", "", &dyn_tracker_tunerConfig::aggro_multi)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.debug_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.debug_mode = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.debug_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<bool>("debug_mode", "bool", 0, "activate/deactivate prints for debugging", "", &dyn_tracker_tunerConfig::debug_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<bool>("debug_mode", "bool", 0, "activate/deactivate prints for debugging", "", &dyn_tracker_tunerConfig::debug_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publish_static = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publish_static = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publish_static = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<bool>("publish_static", "bool", 0, "activate/deactivate publishing of static obstacles", "", &dyn_tracker_tunerConfig::publish_static)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<bool>("publish_static", "bool", 0, "activate/deactivate publishing of static obstacles", "", &dyn_tracker_tunerConfig::publish_static)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noMemoryMode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noMemoryMode = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noMemoryMode = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<bool>("noMemoryMode", "bool", 0, "sets tracking into no Memory mode", "", &dyn_tracker_tunerConfig::noMemoryMode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<bool>("noMemoryMode", "bool", 0, "sets tracking into no Memory mode", "", &dyn_tracker_tunerConfig::noMemoryMode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_obs_size = 5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_obs_size = 40;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_obs_size = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<int>("min_obs_size", "int", 0, "minimum cloud point size of an obstacle", "", &dyn_tracker_tunerConfig::min_obs_size)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<int>("min_obs_size", "int", 0, "minimum cloud point size of an obstacle", "", &dyn_tracker_tunerConfig::min_obs_size)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_obs_size = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_obs_size = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_obs_size = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("max_obs_size", "double", 0, "maximum size of an obstacle in meters", "", &dyn_tracker_tunerConfig::max_obs_size)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("max_obs_size", "double", 0, "maximum size of an obstacle in meters", "", &dyn_tracker_tunerConfig::max_obs_size)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_viewing_distance = 3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_viewing_distance = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_viewing_distance = 9.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("max_viewing_distance", "double", 0, " max reliable distance from the LiDAR", "", &dyn_tracker_tunerConfig::max_viewing_distance)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("max_viewing_distance", "double", 0, " max reliable distance from the LiDAR", "", &dyn_tracker_tunerConfig::max_viewing_distance)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.boundaries_inflation = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.boundaries_inflation = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.boundaries_inflation = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("boundaries_inflation", "double", 0, "Offset of the track boundaries towards the center", "", &dyn_tracker_tunerConfig::boundaries_inflation)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr(new dyn_tracker_tunerConfig::ParamDescription<double>("boundaries_inflation", "double", 0, "Offset of the track boundaries towards the center", "", &dyn_tracker_tunerConfig::boundaries_inflation)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(dyn_tracker_tunerConfig::AbstractGroupDescriptionConstPtr(new dyn_tracker_tunerConfig::GroupDescription<dyn_tracker_tunerConfig::DEFAULT, dyn_tracker_tunerConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<dyn_tracker_tunerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<dyn_tracker_tunerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    dyn_tracker_tunerConfig __max__;
    dyn_tracker_tunerConfig __min__;
    dyn_tracker_tunerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const dyn_tracker_tunerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static dyn_tracker_tunerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &dyn_tracker_tunerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const dyn_tracker_tunerConfig &dyn_tracker_tunerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const dyn_tracker_tunerConfig &dyn_tracker_tunerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const dyn_tracker_tunerConfig &dyn_tracker_tunerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<dyn_tracker_tunerConfig::AbstractParamDescriptionConstPtr> &dyn_tracker_tunerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<dyn_tracker_tunerConfig::AbstractGroupDescriptionConstPtr> &dyn_tracker_tunerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const dyn_tracker_tunerConfigStatics *dyn_tracker_tunerConfig::__get_statics__()
  {
    const static dyn_tracker_tunerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = dyn_tracker_tunerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __DYN_TRACKER_TUNERRECONFIGURATOR_H__
