// Generated by gencpp from file f110_msgs/WpntArray.msg
// DO NOT EDIT!


#ifndef F110_MSGS_MESSAGE_WPNTARRAY_H
#define F110_MSGS_MESSAGE_WPNTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <f110_msgs/Wpnt.h>

namespace f110_msgs
{
template <class ContainerAllocator>
struct WpntArray_
{
  typedef WpntArray_<ContainerAllocator> Type;

  WpntArray_()
    : header()
    , wpnts()  {
    }
  WpntArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , wpnts(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::f110_msgs::Wpnt_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::f110_msgs::Wpnt_<ContainerAllocator> >> _wpnts_type;
  _wpnts_type wpnts;





  typedef boost::shared_ptr< ::f110_msgs::WpntArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f110_msgs::WpntArray_<ContainerAllocator> const> ConstPtr;

}; // struct WpntArray_

typedef ::f110_msgs::WpntArray_<std::allocator<void> > WpntArray;

typedef boost::shared_ptr< ::f110_msgs::WpntArray > WpntArrayPtr;
typedef boost::shared_ptr< ::f110_msgs::WpntArray const> WpntArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f110_msgs::WpntArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f110_msgs::WpntArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::f110_msgs::WpntArray_<ContainerAllocator1> & lhs, const ::f110_msgs::WpntArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.wpnts == rhs.wpnts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::f110_msgs::WpntArray_<ContainerAllocator1> & lhs, const ::f110_msgs::WpntArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace f110_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::WpntArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f110_msgs::WpntArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::WpntArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_msgs::WpntArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::WpntArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_msgs::WpntArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f110_msgs::WpntArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f862195689eef47cf0c81faffd1f380d";
  }

  static const char* value(const ::f110_msgs::WpntArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf862195689eef47cULL;
  static const uint64_t static_value2 = 0xf0c81faffd1f380dULL;
};

template<class ContainerAllocator>
struct DataType< ::f110_msgs::WpntArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f110_msgs/WpntArray";
  }

  static const char* value(const ::f110_msgs::WpntArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f110_msgs::WpntArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Wpnt[] wpnts\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: f110_msgs/Wpnt\n"
"int32 id\n"
"\n"
"# frenet coordinates\n"
"float64 s_m\n"
"float64 d_m\n"
"\n"
"# map coordinates\n"
"float64 x_m\n"
"float64 y_m\n"
"\n"
"# track bound distance\n"
"float64 d_right\n"
"float64 d_left\n"
"\n"
"# track information\n"
"float64 psi_rad\n"
"float64 kappa_radpm\n"
"float64 vx_mps\n"
"float64 ax_mps2\n"
"\n"
;
  }

  static const char* value(const ::f110_msgs::WpntArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f110_msgs::WpntArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.wpnts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WpntArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f110_msgs::WpntArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::f110_msgs::WpntArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "wpnts[]" << std::endl;
    for (size_t i = 0; i < v.wpnts.size(); ++i)
    {
      s << indent << "  wpnts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::f110_msgs::Wpnt_<ContainerAllocator> >::stream(s, indent + "    ", v.wpnts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // F110_MSGS_MESSAGE_WPNTARRAY_H
